@extends('layouts.common')
@section('main')
    <div id="home">
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
        HOME <br>
    </div>
    <div id="features">
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
        FEATURE <br>
    </div>

    <div id="pricing">
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
        PRICING <br>
    </div>
    <div id="testimonials">
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
        TESTIMONIALS <br>
    </div>
@endsection